// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-2XVW57elkPMX4DsD8pbU6iY5rMiBSM',
    appId: '1:135277017788:web:a9f33834eba9343101eeb9',
    messagingSenderId: '135277017788',
    projectId: 'grocify-b90b4',
    authDomain: 'grocify-b90b4.firebaseapp.com',
    storageBucket: 'grocify-b90b4.appspot.com',
    measurementId: 'G-SE19EPSPDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGA_nKaKXsMJ7x6Yil50o0uV8FMui62Mc',
    appId: '1:135277017788:android:659ae8bd42fd70bd01eeb9',
    messagingSenderId: '135277017788',
    projectId: 'grocify-b90b4',
    storageBucket: 'grocify-b90b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawnGLv0ygnC8U0t0EaS2T9-TPVWxoPAk',
    appId: '1:135277017788:ios:0cc0e47ad6fcf60601eeb9',
    messagingSenderId: '135277017788',
    projectId: 'grocify-b90b4',
    storageBucket: 'grocify-b90b4.appspot.com',
    androidClientId: '135277017788-tq7s0tvt00tf7igo6ldad52b2mst2q85.apps.googleusercontent.com',
    iosClientId: '135277017788-hk6r0tlscmkh5avv4qviq87cbuopbk0f.apps.googleusercontent.com',
    iosBundleId: 'com.dev.mvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawnGLv0ygnC8U0t0EaS2T9-TPVWxoPAk',
    appId: '1:135277017788:ios:0cc0e47ad6fcf60601eeb9',
    messagingSenderId: '135277017788',
    projectId: 'grocify-b90b4',
    storageBucket: 'grocify-b90b4.appspot.com',
    androidClientId: '135277017788-tq7s0tvt00tf7igo6ldad52b2mst2q85.apps.googleusercontent.com',
    iosClientId: '135277017788-hk6r0tlscmkh5avv4qviq87cbuopbk0f.apps.googleusercontent.com',
    iosBundleId: 'com.dev.mvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-2XVW57elkPMX4DsD8pbU6iY5rMiBSM',
    appId: '1:135277017788:web:f10d5c1e5528d16901eeb9',
    messagingSenderId: '135277017788',
    projectId: 'grocify-b90b4',
    authDomain: 'grocify-b90b4.firebaseapp.com',
    storageBucket: 'grocify-b90b4.appspot.com',
    measurementId: 'G-H2V6WLLY09',
  );
}
